### ISSUE TITLE
bash config.sh

### ISSUE THREAD

**Issue by lijiaying-cell** [megvii-model/DetNAS#24]
Hello, when I perform bash config.sh appear
nvcc fatal   : Unsupported gpu architecture 'compute_75
How can I solve it

**Comment by yukang2017** [comment]
Hi, would you please provide the complete error logs?

**Comment by lijiaying-cell** [comment]
@yukang2017 
Hello, I have solved the above problem, because cuda version does not match.
Now I have another problem:

Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 

Then, I change 'scripts/run_detnas_coco_fpn_300M_search.sh' export NGPUS=8 to export NGPUS=1,Here comes the problem again:

Traceback (most recent call last):
  File "tools/train_net.py", line 19, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/mnt/DetNAS/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/mnt/DetNAS/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/mnt/DetNAS/maskrcnn_benchmark/data/datasets/__init__.py", line 3, in <module>
    from .coco import COCODataset
  File "/mnt/DetNAS/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    import torchvision
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import models
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 43, in <module>
    @torch.jit._script_if_tracing
AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'
Traceback (most recent call last):
  File "tools/train_net.py", line 19, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/mnt/DetNAS/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/mnt/DetNAS/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/mnt/DetNAS/maskrcnn_benchmark/data/datasets/__init__.py", line 3, in <module>
    from .coco import COCODataset
  File "/mnt/DetNAS/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    import torchvision
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import models
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 43, in <module>
    @torch.jit._script_if_tracing
AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/user/anaconda3/envs/detnas/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/anaconda3/envs/detnas/bin/python3', '-u', 'tools/train_net.py', '--local_rank=1', '--config-file', 'configs/e2e_faster_rcnn_DETNAS_COCO_FPN_300M_search.yaml', 'OUTPUT_DIR', 'models/DETNAS_COCO_FPN_300M_1x_search']' returned non-zero exit status 1.

**Comment by ytoon** [comment]
OMP_NUM_THREADS(number of threads) is different from NGPUS(gpu nums).  You should change the value in https://github.com/megvii-model/DetNAS/blob/aa92a90604c870fcb7e3ea9f60d16e6f107454d9/maskrcnn_benchmark/config/defaults.py#L79. Or refer to https://github.com/pytorch/pytorch/issues/16894#issuecomment-513515589.
