### ISSUE TITLE
HELP！many issuea，but i flow your tips

### ISSUE THREAD

**Issue by Aurora-Rong** [megvii-model/DetNAS#37]
$ bash scripts/run_detnas_coco_fpn_300M_search.sh
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "tools/train_net.py", line 19, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/__init__.py", line 3, in <module>
    from .coco import COCODataset
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    import torchvision
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/__init__.py", line 3, in <module>
    from torchvision import models
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 11, in <module>
    from . import _utils as det_utils
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py", line 19, in <module>
    class BalancedPositiveNegativeSampler(object):
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1219, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1076, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 222, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1226, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError:
builtin cannot be used as a value:
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:14:56
def zeros_like(tensor, dtype):
    # type: (Tensor, int) -> Tensor
    return torch.zeros_like(tensor, dtype=dtype, layout=tensor.layout,
                                                        ~~~~~~~~~~~~~ <--- HERE
                            device=tensor.device, pin_memory=tensor.is_pinned())
'zeros_like' is being compiled since it was called from '__torch__.torchvision.models.detection._utils.BalancedPositiveNegativeSampler.__call__'
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:72:12

            # randomly select positive and negative examples
            perm1 = torch.randperm(positive.numel(), device=positive.device)[:num_pos]
            perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]

            pos_idx_per_image = positive[perm1]
            neg_idx_per_image = negative[perm2]

            # create binary mask from indices
            pos_idx_per_image_mask = zeros_like(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                matched_idxs_per_image, dtype=torch.uint8
            )
            neg_idx_per_image_mask = zeros_like(
                matched_idxs_per_image, dtype=torch.uint8
            )

            pos_idx_per_image_mask[pos_idx_per_image] = torch.tensor(1, dtype=torch.uint8)
            neg_idx_per_image_mask[neg_idx_per_image] = torch.tensor(1, dtype=torch.uint8)

Traceback (most recent call last):
  File "tools/train_net.py", line 19, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/__init__.py", line 3, in <module>
    from .coco import COCODataset
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    import torchvision
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/__init__.py", line 3, in <module>
    from torchvision import models
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 11, in <module>
    from . import _utils as det_utils
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py", line 19, in <module>
    class BalancedPositiveNegativeSampler(object):
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1219, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1076, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 222, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1226, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError:
builtin cannot be used as a value:
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:14:56
def zeros_like(tensor, dtype):
    # type: (Tensor, int) -> Tensor
    return torch.zeros_like(tensor, dtype=dtype, layout=tensor.layout,
                                                        ~~~~~~~~~~~~~ <--- HERE
                            device=tensor.device, pin_memory=tensor.is_pinned())
'zeros_like' is being compiled since it was called from '__torch__.torchvision.models.detection._utils.BalancedPositiveNegativeSampler.__call__'
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:72:12

            # randomly select positive and negative examples
            perm1 = torch.randperm(positive.numel(), device=positive.device)[:num_pos]
            perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]

            pos_idx_per_image = positive[perm1]
            neg_idx_per_image = negative[perm2]

            # create binary mask from indices
            pos_idx_per_image_mask = zeros_like(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                matched_idxs_per_image, dtype=torch.uint8
            )
            neg_idx_per_image_mask = zeros_like(
                matched_idxs_per_image, dtype=torch.uint8
            )

            pos_idx_per_image_mask[pos_idx_per_image] = torch.tensor(1, dtype=torch.uint8)
            neg_idx_per_image_mask[neg_idx_per_image] = torch.tensor(1, dtype=torch.uint8)
Traceback (most recent call last):
  File "tools/train_net.py", line 19, in <module>

    from maskrcnn_benchmark.data import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/__init__.py", line 3, in <module>
    from .coco import COCODataset
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    import torchvision
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/__init__.py", line 3, in <module>
    from torchvision import models
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 11, in <module>
    from . import _utils as det_utils
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py", line 19, in <module>
    class BalancedPositiveNegativeSampler(object):
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1219, in script
Traceback (most recent call last):
  File "tools/train_net.py", line 19, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/__init__.py", line 3, in <module>
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1076, in _compile_and_register_class
    from .coco import COCODataset
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    import torchvision
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/__init__.py", line 3, in <module>
    from torchvision import models
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>
    _jit_script_class_compile(qualified_name, ast, rcb)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 222, in try_compile_fn
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 11, in <module>
    return torch.jit.script(fn, _rcb=rcb)
    from . import _utils as det_utils
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py", line 19, in <module>
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1226, in script
    class BalancedPositiveNegativeSampler(object):
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1219, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError:
builtin cannot be used as a value:
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:14:56
def zeros_like(tensor, dtype):
    # type: (Tensor, int) -> Tensor
    return torch.zeros_like(tensor, dtype=dtype, layout=tensor.layout,
                                                        ~~~~~~~~~~~~~ <--- HERE
                            device=tensor.device, pin_memory=tensor.is_pinned())
'zeros_like' is being compiled since it was called from '__torch__.torchvision.models.detection._utils.BalancedPositiveNegativeSampler.__call__'
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:72:12

            # randomly select positive and negative examples
            perm1 = torch.randperm(positive.numel(), device=positive.device)[:num_pos]
            perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]

            pos_idx_per_image = positive[perm1]
            neg_idx_per_image = negative[perm2]

            # create binary mask from indices
            pos_idx_per_image_mask = zeros_like(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                matched_idxs_per_image, dtype=torch.uint8
            )
            neg_idx_per_image_mask = zeros_like(
                matched_idxs_per_image, dtype=torch.uint8
            )

            pos_idx_per_image_mask[pos_idx_per_image] = torch.tensor(1, dtype=torch.uint8)
            neg_idx_per_image_mask[neg_idx_per_image] = torch.tensor(1, dtype=torch.uint8)

    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1076, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 222, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1226, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError:
builtin cannot be used as a value:
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:14:56
def zeros_like(tensor, dtype):
    # type: (Tensor, int) -> Tensor
    return torch.zeros_like(tensor, dtype=dtype, layout=tensor.layout,
                                                        ~~~~~~~~~~~~~ <--- HERE
                            device=tensor.device, pin_memory=tensor.is_pinned())
'zeros_like' is being compiled since it was called from '__torch__.torchvision.models.detection._utils.BalancedPositiveNegativeSampler.__call__'
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:72:12

            # randomly select positive and negative examples
            perm1 = torch.randperm(positive.numel(), device=positive.device)[:num_pos]
            perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]

            pos_idx_per_image = positive[perm1]
            neg_idx_per_image = negative[perm2]

            # create binary mask from indices
            pos_idx_per_image_mask = zeros_like(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                matched_idxs_per_image, dtype=torch.uint8
            )
            neg_idx_per_image_mask = zeros_like(
                matched_idxs_per_image, dtype=torch.uint8
            )

            pos_idx_per_image_mask[pos_idx_per_image] = torch.tensor(1, dtype=torch.uint8)
            neg_idx_per_image_mask[neg_idx_per_image] = torch.tensor(1, dtype=torch.uint8)

Traceback (most recent call last):
  File "tools/train_net.py", line 19, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/__init__.py", line 3, in <module>
    from .coco import COCODataset
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    import torchvision
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/__init__.py", line 3, in <module>
    from torchvision import models
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 11, in <module>
    from . import _utils as det_utils
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py", line 19, in <module>
    class BalancedPositiveNegativeSampler(object):
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1219, in script
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/train_net.py", line 19, in <module>
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1076, in _compile_and_register_class
Traceback (most recent call last):
  File "tools/train_net.py", line 19, in <module>
  File "tools/train_net.py", line 19, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from .build import make_data_loader
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/__init__.py", line 3, in <module>
    from . import datasets as D
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/__init__.py", line 3, in <module>
    _jit_script_class_compile(qualified_name, ast, rcb)
    from .coco import COCODataset
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 222, in try_compile_fn
    from .coco import COCODataset
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    from .build import make_data_loader
import torchvision
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/build.py", line 11, in <module>
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/__init__.py", line 3, in <module>
    import torchvision
      File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/__init__.py", line 3, in <module>
from torchvision import models
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/__init__.py", line 12, in <module>
from . import datasets as D
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/__init__.py", line 3, in <module>
    from torchvision import models
from . import detection
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/__init__.py", line 12, in <module>
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
        from .coco import COCODataset
from .faster_rcnn import *from . import detection

  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>
  File "/home/mist/DetNAS-master/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
return torch.jit.script(fn, _rcb=rcb)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1226, in script
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
from .faster_rcnn import *  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 11, in <module>

    import torchvision  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>

  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/__init__.py", line 3, in <module>
    from . import _utils as det_utils
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py", line 19, in <module>
        from .rpn import AnchorGenerator, RPNHead, RegionProposalNetworkfrom torchvision import models

  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/__init__.py", line 12, in <module>
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 11, in <module>
    class BalancedPositiveNegativeSampler(object):
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1219, in script
        from . import detectionfrom . import _utils as det_utils

  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py", line 19, in <module>
        class BalancedPositiveNegativeSampler(object):
from .faster_rcnn import *  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1219, in script

  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 11, in <module>
    from . import _utils as det_utils
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py", line 19, in <module>
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
    RuntimeError_compile_and_register_class(obj, _rcb, qualified_name):

builtin cannot be used as a value:
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:14:56
def zeros_like(tensor, dtype):
    # type: (Tensor, int) -> Tensor
    return torch.zeros_like(tensor, dtype=dtype, layout=tensor.layout,
                                                        ~~~~~~~~~~~~~ <--- HERE
                            device=tensor.device, pin_memory=tensor.is_pinned())
'zeros_like' is being compiled since it was called from '__torch__.torchvision.models.detection._utils.BalancedPositiveNegativeSampler.__call__'
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:72:12

            # randomly select positive and negative examples
            perm1 = torch.randperm(positive.numel(), device=positive.device)[:num_pos]
            perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]

            pos_idx_per_image = positive[perm1]
            neg_idx_per_image = negative[perm2]

            # create binary mask from indices
            pos_idx_per_image_mask = zeros_like(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                matched_idxs_per_image, dtype=torch.uint8
            )
            neg_idx_per_image_mask = zeros_like(
                matched_idxs_per_image, dtype=torch.uint8
            )

            pos_idx_per_image_mask[pos_idx_per_image] = torch.tensor(1, dtype=torch.uint8)
            neg_idx_per_image_mask[neg_idx_per_image] = torch.tensor(1, dtype=torch.uint8)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1076, in _compile_and_register_class

    class BalancedPositiveNegativeSampler(object):
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1219, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1076, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 222, in try_compile_fn
        _compile_and_register_class(obj, _rcb, qualified_name)return torch.jit.script(fn, _rcb=rcb)
    _jit_script_class_compile(qualified_name, ast, rcb)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1226, in script
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 222, in try_compile_fn

  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1076, in _compile_and_register_class
    return torch.jit.script(fn, _rcb=rcb)
      File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1226, in script
fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError:     _jit_script_class_compile(qualified_name, ast, rcb)
builtin cannot be used as a value:
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:14:56
def zeros_like(tensor, dtype):
    # type: (Tensor, int) -> Tensor
    return torch.zeros_like(tensor, dtype=dtype, layout=tensor.layout,
                                                        ~~~~~~~~~~~~~ <--- HERE
                            device=tensor.device, pin_memory=tensor.is_pinned())
'zeros_like' is being compiled since it was called from '__torch__.torchvision.models.detection._utils.BalancedPositiveNegativeSampler.__call__'
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:72:12

            # randomly select positive and negative examples
            perm1 = torch.randperm(positive.numel(), device=positive.device)[:num_pos]
            perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]

            pos_idx_per_image = positive[perm1]
            neg_idx_per_image = negative[perm2]

            # create binary mask from indices
            pos_idx_per_image_mask = zeros_like(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                matched_idxs_per_image, dtype=torch.uint8
            )
            neg_idx_per_image_mask = zeros_like(
                matched_idxs_per_image, dtype=torch.uint8
            )

            pos_idx_per_image_mask[pos_idx_per_image] = torch.tensor(1, dtype=torch.uint8)
            neg_idx_per_image_mask[neg_idx_per_image] = torch.tensor(1, dtype=torch.uint8)


  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 222, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1226, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError:
builtin cannot be used as a value:
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:14:56
def zeros_like(tensor, dtype):
    # type: (Tensor, int) -> Tensor
    return torch.zeros_like(tensor, dtype=dtype, layout=tensor.layout,
                                                        ~~~~~~~~~~~~~ <--- HERE
                            device=tensor.device, pin_memory=tensor.is_pinned())
'zeros_like' is being compiled since it was called from '__torch__.torchvision.models.detection._utils.BalancedPositiveNegativeSampler.__call__'
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:72:12

            # randomly select positive and negative examples
            perm1 = torch.randperm(positive.numel(), device=positive.device)[:num_pos]
            perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]

            pos_idx_per_image = positive[perm1]
            neg_idx_per_image = negative[perm2]

            # create binary mask from indices
            pos_idx_per_image_mask = zeros_like(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                matched_idxs_per_image, dtype=torch.uint8
            )
            neg_idx_per_image_mask = zeros_like(
                matched_idxs_per_image, dtype=torch.uint8
            )

            pos_idx_per_image_mask[pos_idx_per_image] = torch.tensor(1, dtype=torch.uint8)
            neg_idx_per_image_mask[neg_idx_per_image] = torch.tensor(1, dtype=torch.uint8)

    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError:
builtin cannot be used as a value:
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:14:56
def zeros_like(tensor, dtype):
    # type: (Tensor, int) -> Tensor
    return torch.zeros_like(tensor, dtype=dtype, layout=tensor.layout,
                                                        ~~~~~~~~~~~~~ <--- HERE
                            device=tensor.device, pin_memory=tensor.is_pinned())
'zeros_like' is being compiled since it was called from '__torch__.torchvision.models.detection._utils.BalancedPositiveNegativeSampler.__call__'
at /mistgpu/miniconda/lib/python3.7/site-packages/torchvision/models/detection/_utils.py:72:12

            # randomly select positive and negative examples
            perm1 = torch.randperm(positive.numel(), device=positive.device)[:num_pos]
            perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]

            pos_idx_per_image = positive[perm1]
            neg_idx_per_image = negative[perm2]

            # create binary mask from indices
            pos_idx_per_image_mask = zeros_like(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
                matched_idxs_per_image, dtype=torch.uint8
            )
            neg_idx_per_image_mask = zeros_like(
                matched_idxs_per_image, dtype=torch.uint8
            )

            pos_idx_per_image_mask[pos_idx_per_image] = torch.tensor(1, dtype=torch.uint8)
            neg_idx_per_image_mask[neg_idx_per_image] = torch.tensor(1, dtype=torch.uint8)

Traceback (most recent call last):
  File "/mistgpu/miniconda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mistgpu/miniconda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/mistgpu/miniconda/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/mistgpu/miniconda/bin/python3', '-u', 'tools/train_net.py', '--local_rank=7', '--config-file', 'configs/e2e_faster_rcnn_DETNAS_COCO_FPN_300M_search.yaml', 'OUTPUT_DIR', 'models/DETNAS_COCO_FPN_300M_1x_search']' returned non-zero exit status 1.

**Comment by yukang2017** [comment]
Sorry for the late reply. I thinks this issue might comes from the installation. Would you please show your torch and torchvision version?
